/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : kb
 * Created : 06/21/2013
 */

package eu.dm2e.ws.grafeo.junit;

import org.junit.Ignore;
import org.junit.Test;

import eu.dm2e.ws.OmnomUnitTest;
import eu.dm2e.ws.grafeo.GResource;
import eu.dm2e.ws.grafeo.Grafeo;
import eu.dm2e.ws.grafeo.jena.GrafeoImpl;



public class GrafeoAssertTest extends OmnomUnitTest {

	/**
	 *
	 * @see eu.dm2e.ws.grafeo.junit.GrafeoAssert#containsResource(Grafeo,Object,Object,Object)
	 */
	@Test
	public void containsResource() {
		Grafeo grafeo = new GrafeoImpl();
		grafeo.addTriple("omnom:foo", "omnom:bar", "omnom:baz");
		log.info(grafeo.getNTriples());
		GrafeoAssert.containsResource(grafeo,"omnom:foo",null,null);
	}
	
	@Test
	@Ignore
	public void graphsAreStructurallyEquivalent() { 
		Grafeo g1 = new GrafeoImpl();
		GResource res1 = g1.createBlank();
		GResource blank1 = g1.createBlank();
		res1.set("omnom:baz", blank1);
		g1.addTriple(blank1, "omnom:foo", g1.literal("bar"));
		
		Grafeo g2 = new GrafeoImpl();
		GResource res2 = g2.resource("NOT_BLANK");
		GResource blank2 = g2.createBlank();
		res2.set("omnom:baz", blank2);
		g2.addTriple(blank2, "omnom:foo", g2.literal("bar"));
		
		log.info(g1.getPredicateSortedNTriples());
		log.info(g2.getPredicateSortedNTriples());
		GrafeoAssert.sizeEquals(g1, g2);
		GrafeoAssert.graphsAreStructurallyEquivalent(g1, g2);
	}

	
}
